### ISSUE TITLE
Trying it on gcc8.2, it doesn't seem to work

### ISSUE THREAD

**Issue by Fin-chan** [royjacobson/externis#3]
`cc1plus: error: cannot load plugin /data/code/github/externis/externis.so`
`   /data/root/gcc-8.2.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /data/code/github/externis/externis.so)`

I use gcc12 to compile externis, but using it on a gcc8.2 application doesn't work!

**Comment by andrewauclair** [comment]
You can't link libraries built with newer gcc versions into executables built with an older gcc. You'll have to build externis and the application with the same versions of gcc.

**Comment by royjacobson** [comment]
Basically what @andrewauclair said. Sorry :/
